# Generated by Django 4.0.3 on 2022-04-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='user',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
